export const ERROR_MESSAGE_MAP: { [key: string]: string } = {
    "auth/account-exists-with-different-credential": "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.",
    "auth/admin-restricted-operation": "This operation can only be performed by an admin.",
    "auth/already-initialized": "The library has already been initialized. We recommend calling initializeApp() directly.",
    "auth/app-deleted": "The app has been deleted. Please reinstall or restore the app.",
    "auth/app-not-authorized": "This app is not authorized to perform this operation.",
    "auth/app-not-installed": "The app needs to be installed for this operation.",
    "auth/argument-error": "Invalid arguments provided.",
    "auth/auth-domain-config-required": "Authentication domain configuration is required.",
    "auth/cancelled-popup-request": "The popup request was cancelled. Please try again.",
    "auth/captcha-check-failed": "Failed to verify the CAPTCHA. Please try again.",
    "auth/code-expired": "The verification code has expired. Request a new one.",
    "auth/cordova-not-ready": "Cordova environment is not ready. Please wait.",
    "auth/cors-unsupported": "Your browser does not support Cross-origin resource sharing (CORS).",
    "auth/credential-already-in-use": "These credentials are already associated with another user.",
    "auth/custom-token-mismatch": "The custom token does not match with the credential.",
    "auth/dependent-sdk-initialized-before-auth": "The Authentication SDK should be initialized before the dependent SDKs.",
    "auth/dynamic-link-not-activated": "Please activate the dynamic link to proceed.",
    "auth/email-already-in-use": "The email address is already associated with another account.",
    "auth/email-change-needs-verification": "The change in email requires verification. Check your inbox.",
    "auth/emulator-config-failed": "Failed to configure the emulator. Please check your setup.",
    "auth/expired-action-code": "The action code has expired. Request a new one.",
    "auth/internal-error": "An internal error occurred. Please try again.",
    "auth/invalid-action-code": "The action code is invalid or expired.",
    "auth/invalid-api-key": "The provided API key is invalid.",
    "auth/invalid-app-credential": "The app credential is invalid or expired.",
    "auth/invalid-app-id": "The app ID is invalid or does not match with any existing apps.",
    "auth/invalid-auth-event": "The authentication event is invalid or expired.",
    "auth/invalid-cert-hash": "The certificate hash is invalid or does not match with our records.",
    "auth/invalid-continue-uri": "The continue URL is not valid. Please provide a valid URL.",
    "auth/invalid-cordova-configuration": "The configuration of Cordova is invalid.",
    "auth/invalid-credential": "The provided credential is invalid or expired.",
    "auth/invalid-custom-token": "The custom token provided is invalid. Please check the token and try again.",
    "auth/invalid-dynamic-link-domain": "The dynamic link domain is not valid. Please provide a valid domain.",
    "auth/invalid-email": "The email address provided is invalid. Please provide a valid email address.",
    "auth/invalid-emulator-scheme": "The emulator scheme is invalid or not configured correctly.",
    "auth/invalid-login-credentials": "You have invalid login credentials. Please use the correct credentials.",
    "auth/invalid-message-payload": "The message payload is invalid. Please provide a valid payload.",
    "auth/invalid-multi-factor-session": "The multi-factor authentication session is invalid or expired.",
    "auth/invalid-oauth-client-id": "The OAuth client ID provided is invalid.",
    "auth/invalid-oauth-provider": "The OAuth provider specified is not supported or is not valid.",
    "auth/invalid-persistence-type": "The type of persistence is invalid or not supported in this environment.",
    "auth/invalid-phone-number": "The phone number provided is invalid. Please provide a valid phone number.",
    "auth/invalid-provider-id": "The provider ID provided is invalid.",
    "auth/invalid-recaptcha-action": "The recaptcha action is invalid. Please provide a valid recaptcha action.",
    "auth/invalid-recaptcha-token": "The recaptcha token is invalid. Please provide a valid recaptcha token.",
    "auth/invalid-recaptcha-version": "The recaptcha version is invalid. Please provide a valid recaptcha version.",
    "auth/invalid-recipient-email": "The recipient email is invalid. Please provide a valid email address.",
    "auth/invalid-req-type": "The request type is invalid. Please provide a valid request type.",
    "auth/invalid-sender": "The sender is invalid. Please provide a valid sender.",
    "auth/invalid-tenant-id": "The tenant ID is invalid or not found.",
    "auth/invalid-user-token": "The user token is invalid, expired, or does not match with our records.",
    "auth/invalid-verification-code": "The verification code is invalid or expired.",
    "auth/invalid-verification-id": "The verification ID is invalid or expired.",
    "auth/maximum-second-factor-count-exceeded": "The maximum allowed number of second factors on a user has been exceeded.",
    "auth/missing-android-pkg-name": "The Android package name is missing. Please provide the package name.",
    "auth/missing-app-credential": "The app credential is missing. Please provide the app credential.",
    "auth/missing-client-type": "The client type is missing. Please provide the client type.",
    "auth/missing-continue-uri": "The continue URL is missing. Please provide the continue URL.",
    "auth/missing-iframe-start": "The start of the iframe is missing.",
    "auth/missing-ios-bundle-id": "The iOS bundle ID is missing. Please provide the bundle ID.",
    "auth/missing-multi-factor-info": "The multi-factor information is missing. Please provide multi-factor information.",
    "auth/missing-multi-factor-session": "The multi-factor session is missing. Please provide a multi-factor session.",
    "auth/missing-or-invalid-nonce": "The nonce is missing or invalid.",
    "auth/missing-phone-number": "The phone number is missing. Please provide the phone number.",
    "auth/missing-recaptcha-token": "The recaptcha token is missing. Please provide the recaptcha token and try again.",
    "auth/missing-recaptcha-version": "The recaptcha version is missing. Please provide the recaptcha version.",
    "auth/missing-verification-code": "The verification code is missing. Please provide the verification code.",
    "auth/missing-verification-id": "The verification ID is missing. Please provide the verification ID.",
    "auth/multi-factor-auth-required": "Multi-factor authentication is required for this operation. Please authenticate and try again.",
    "auth/multi-factor-info-not-found": "The multi-factor information was not found. Please provide valid multi-factor information.",
    "auth/network-request-failed": "A network error has occurred (such as timeout, interrupted connection or unreachable host). Please try again.",
    "auth/no-auth-event": "No authentication event could be found or processed.",
    "auth/no-such-provider": "No provider corresponds to the provided provider identifier.",
    "auth/null-user": "No user is currently signed in.",
    "auth/operation-not-allowed": "This operation is not allowed. Check the authentication methods and try again.",
    "auth/operation-not-supported-in-this-environment": "This operation is not supported in the current environment. Use a supported environment and try again.",
    "auth/popup-blocked": "The popup has been blocked by the browser. Please enable popups and try again.",
    "auth/popup-closed-by-user": "The popup has been closed by the user before finalizing the operation.",
    "auth/provider-already-linked": "The provider has already been linked to the user and cannot be linked again.",
    "auth/quota-exceeded": "The project's quota for this operation has been exceeded.",
    "auth/recaptcha-not-enabled": "Recaptcha is not enabled. Please enable Recaptcha and try again.",
    "auth/redirect-cancelled-by-user": "The redirect operation has been cancelled by the user before finalizing.",
    "auth/redirect-operation-pending": "A redirect sign-in operation is already in progress.",
    "auth/rejected-credential": "The request contained a credential that has been rejected.",
    "auth/requires-recent-login": "This operation is sensitive and requires recent authentication. Please login again.",
    "auth/second-factor-already-in-use": "The second factor is already enrolled on this account.",
    "auth/tenant-id-mismatch": "The provided tenant ID does not match the expected tenant ID.",
    "auth/timeout": "The operation has timed out. Please try again.",
    "auth/too-many-requests": "We have blocked all requests from this device due to unusual activity. Try again later.",
    "auth/unauthorized-continue-uri": "The domain of the continue URL is not authorized.",
    "auth/unauthorized-domain": "The domain of the continue URL is not whitelisted. Please provide a whitelisted domain.",
    "auth/unsupported-first-factor": "The sign-in method for the first factor is not supported.",
    "auth/unsupported-persistence-type": "The current environment does not support the specified persistence type.",
    "auth/unsupported-tenant-operation": "The operation is not supported in a multi-tenant context.",
    "auth/unverified-email": "The email is not verified. Please verify the email before continuing.",
    "auth/user-cancelled": "The user did not grant your application the permissions it requested.",
    "auth/user-disabled": "The user account has been disabled by an administrator.",
    "auth/user-mismatch": "The supplied credentials do not correspond to the previously signed in user.",
    "auth/user-not-found": "There is no user corresponding to the credentials provided.",
    "auth/user-signed-out": "The user has been signed out.",
    "auth/user-token-expired": "The user's credential is no longer valid. The user must sign in again.",
    "auth/weak-password": "The password is too weak. Please provide a stronger password.",
    "auth/web-storage-unsupported": "This browser is not supported or third-party cookies and data may be disabled.",
    "auth/wrong-password": "The password provided is incorrect. Please provide the correct password."
};

// Now modify the getErrorMessageFromCode function to use this map
export function getErrorMessageFromCode(errorCode: string): string {
    return ERROR_MESSAGE_MAP[errorCode] || "An unknown error occurred. Please try again.";
}
