export const FUND_FOCUS = [
  "advanced materials",
  "advertising (adtech)",
  "agtech (farmtech)",
  "apps",
  "artificial intelligence & machine learning (ai/ml)",
  "assistivetech",
  "audiotech",
  "augmented & virtual reality (ar/vr)",
  "b2b",
  "b2c",
  "beauty",
  "big data & analytics",
  "biotech",
  "black / african american founded",
  "cannabis",
  "climatetech & cleantech",
  "cloud security",
  "cloudtech",
  "cms",
  "collaboration",
  "communications infrastructure",
  "community",
  "computer",
  "construction tech",
  "consulting",
  "consumer electronics",
  "consumer goods",
  "consumer internet",
  "consumer",
  "cpg",
  "creator economy",
  "crm",
  "cryptocurrency / blockchain",
  "customer service",
  "cybersecurity",
  "d2c",
  "deeptech",
  "delivery",
  "developer tools",
  "e-commerce",
  "e-sports (gaming)",
  "edtech",
  "elder care",
  "emerging markets",
  "energy",
  "enterprise",
  "entertainment & media",
  "events",
  "fashion",
  "femtech",
  "fintech",
  "food and beverage",
  "foodtech",
  "future of work",
  "govtech",
  "hardware",
  "health & wellness",
  "healthcare",
  "hospitality",
  "hr tech",
  "impact investing",
  "industrials",
  "information technology",
  "infrastructure",
  "insurtech",
  "internet",
  "iot (internet of things)",
  "legal tech",
  "life science",
  "logistics",
  "manufacturing",
  "market research",
  "marketing (martech)",
  "marketplace",
  "medical device",
  "meeting software",
  "micro-mobility",
  "mobile",
  "nanotechnology",
  "network security",
  "neuroscience",
  "oil & gas",
  "outdoors",
  "paas (platforms)",
  "parenting",
  "pettech",
  "pharmaceuticals",
  "pos (point of sale)",
  "privacy",
  "productivity tools",
  "professional services",
  "proptech",
  "quality assurance",
  "recruiting",
  "restauranttech",
  "retailtech",
  "ridesharing",
  "risk management",
  "robotics",
  "saas",
  "sales automation",
  "service industry",
  "sharing economy",
  "simulation",
  "social media",
  "software",
  "spacetech",
  "sports",
  "supply chain tech",
  "sustainability",
  "telecommunications (tmt)",
  "transportation",
  "travel",
  "wearables & quantified self",
  "women-founded",
];